import { Router, type IRouter } from "express";
import healthRouter from "./health.js";
import profilesRouter from "./profiles.js";
import projectsRouter from "./projects.js";
import analyzeRouter from "./analyze.js";
import workspaceRouter from "./workspace.js";
import aiRouter from "./ai.js";
import componentsRouter from "./components.js";
import budgetRouter from "./budget.js";
import blueprintsRouter from "./blueprints.js";
import sharingRouter from "./sharing.js";
import classesRouter from "./classes.js";
import assignmentsRouter from "./assignments.js";
import submissionsRouter from "./submissions.js";
import analyticsRouter from "./analytics.js";
import paymentsRouter from "./payments.js";
import usageRouter from "./usage.js";
import contactRouter from "./contact.js";
import settingsRouter from "./settings.js";
import notificationsRouter from "./notifications.js";
import searchRouter from "./search.js";
import recentlyViewedRouter from "./recently-viewed.js";
import adminRouter from "./admin.js";
import wiringRouter from "./wiring.js";
import feedbackRouter from "./feedback.js";

const router: IRouter = Router();

router.use(healthRouter);
router.use(profilesRouter);
router.use(settingsRouter);
router.use(notificationsRouter);
router.use(analyzeRouter);
router.use(workspaceRouter);
router.use(aiRouter);
router.use(componentsRouter);
router.use(budgetRouter);
router.use(blueprintsRouter);
router.use(sharingRouter);
router.use(classesRouter);
router.use(assignmentsRouter);
router.use(submissionsRouter);
router.use(analyticsRouter);
router.use(paymentsRouter);
router.use(usageRouter);
router.use(contactRouter);
router.use(searchRouter);
router.use(recentlyViewedRouter);
router.use(adminRouter);
router.use(wiringRouter);
router.use("/feedback", feedbackRouter);
router.use(projectsRouter);

export default router;
