import { Router, type IRouter } from "express";
import healthRouter from "./health";
import profilesRouter from "./profiles";
import projectsRouter from "./projects";
import analyzeRouter from "./analyze";
import workspaceRouter from "./workspace";
import aiRouter from "./ai";
import componentsRouter from "./components";
import budgetRouter from "./budget";
import blueprintsRouter from "./blueprints";
import sharingRouter from "./sharing";
import classesRouter from "./classes";
import assignmentsRouter from "./assignments";
import submissionsRouter from "./submissions";
import analyticsRouter from "./analytics";
import paymentsRouter from "./payments";
import usageRouter from "./usage";
import contactRouter from "./contact";
import settingsRouter from "./settings";
import notificationsRouter from "./notifications";

const router: IRouter = Router();

router.use(healthRouter);
router.use(profilesRouter);
router.use(settingsRouter);
router.use(notificationsRouter);
router.use(analyzeRouter);
router.use(workspaceRouter);
router.use(aiRouter);
router.use(componentsRouter);
router.use(budgetRouter);
router.use(blueprintsRouter);
router.use(sharingRouter);
router.use(classesRouter);
router.use(assignmentsRouter);
router.use(submissionsRouter);
router.use(analyticsRouter);
router.use(paymentsRouter);
router.use(usageRouter);
router.use(contactRouter);
router.use(projectsRouter);

export default router;
